const actions = {
    ADD_MEDIA: "ADD_MEDIA",
    ADD_COMMENT: "ADD_COMMENT",
    RATE_MEDIA: "RATE_MEDIA",
    RATE_COMMENT: "RATE_COMMENT",
    GET_MEDIA_LIST: "GET_MEDIA_LIST",
    GET_COMMENT_LIST: "GET_COMMENT_LIST",
    GET_LAST10_MEDIA: "GET_LAST10_MEDIA",
    GET_MOST_VIEWS_MEDIA: "GET_MOST_VIEWS_MEDIA",
}

export default actions