export enum actions {
    ADD_MEDIA = "ADD_MEDIA",
    ADD_COMMENT = "ADD_COMMENT",
    RATE_MEDIA = "RATE_MEDIA",
    RATE_COMMENT = "RATE_COMMENT",
    GET_MEDIA = "GET_MEDIA",
    SET_FILTER = "SET_FILTER",
    GET_COMMENT = "GET_COMMENT",
    GET_COMMENT_LIST ="GET_COMMENT_LIST",
}

export enum VISIBILITY_FILTERS {
    ALL = 'ALL',
    LAST10 = 'LAST10',
    MOST_POPULAR = 'MOST_POPULAR',
}
