export enum AllMediaListActions {
    GET_ALL_MEDIA = 'FETCH_ALL_MEDIA',
    GET_ALL_MEDIA_SUCCESS = 'FETCH_ALL_MEDIA_SUCCESS',
    GET_ALL_MEDIA_ERROR = 'FETCH_ALL_MEDIA_ERROR',
}

export enum UserLoginActions {
    SUBMIT_USER_LOGIN_DATA = 'SUBMIT_USER_LOGIN_DATA',
    GET_USER_PROFILE = 'GET_USER_PROFILE',
    LOGOUT_USER_LOGIN = 'LOGOUT_USER_LOGIN',
}